environment:
  matrix:
  - arch: amd64
    vsver: 120

install:
- ps: install-module pscx -scope CurrentUser

build: off

build_script:
- ps: >-
    .\build.ps1 -arch:$env:arch -vsver:$env:vsver

test: off

after_build:
- cmd: 7z a zlib-bin.zip %APPVEYOR_BUILD_FOLDER%\zlib*.dll
- cmd: 7z a zlib-bin.zip %APPVEYOR_BUILD_FOLDER%\zlib*.lib
- cmd: 7z a zlib-bin.zip %APPVEYOR_BUILD_FOLDER%\zlib*.pdb
- cmd: 7z a zlib-bin.zip %APPVEYOR_BUILD_FOLDER%\*.h

test_script:
- ps: >-
    .\test.ps1 -arch:$env:arch -vsver:$env:vsver

artifacts:
  - path: zlib-bin.zip
    name: zlib-$arch-$vsver
    type: zip
