environment:
  matrix:
  - arch: amd64
    vsver: 120
  - arch: amd64
    vsver: 140

install:
- ps: install-module pscx -scope CurrentUser

build: off

build_script:
- ps: >-
    .\win32\build.ps1 -arch:$env:arch -vsver:$env:vsver

test: off

after_build:
- cmd: 7z a zlib-%arch%-vs%vsver%.zip %APPVEYOR_BUILD_FOLDER%\zlib*.dll > nul
- cmd: 7z a zlib-%arch%-vs%vsver%.zip %APPVEYOR_BUILD_FOLDER%\zlib*.lib > nul
- cmd: 7z a zlib-%arch%-vs%vsver%.zip %APPVEYOR_BUILD_FOLDER%\zlib*.pdb > nul
- cmd: 7z a zlib-%arch%-vs%vsver%.zip %APPVEYOR_BUILD_FOLDER%\*.h > nul

test_script:
- ps: >-
    .\win32\test.ps1 -arch:$env:arch -vsver:$env:vsver

artifacts:
  - path: '*.zip'
    name: bin
    type: zip
