environment:
  matrix:
  - arch: amd64
    vsver: 120

install:
- ps: install-module pscx -scope CurrentUser

build: off

build_script:
- ps: .\win32\build.ps1 -arch:$env:arch -vsver:$env:vsver

test: off

test_script:
- ps: .\win32\test.ps1 -arch:$env:arch -vsver:$env:vsver

after_test:
- ps: nuget pack .\win32\.nuspec

artifacts:
  - path: '*.nupkg'
    name: nupkg
    type: NuGetPackage

deploy:
  provider: NuGet
  api_key:
    secure: 3an8ox7VohU98W6Y/QPmq+Fr3UnpBz92xtfcDZKLuKI=
  artifact: /.*\.nupkg/
