environment:
  matrix:
  - arch: amd64
    vsver: 120
  - arch: amd64
    vsver: 140
  - arch: amd64
    vsver: 90

install:
- ps: install-module pscx -scope CurrentUser

build: off

build_script:
- ps: >-
    .\build.ps1 -arch:$env:arch -vsver:$env:vsver

test: off
